In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from scipy import stats

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
from google.colab import files
uploaded = files.upload()

Saving Book_ipl22_ver_33.csv to Book_ipl22_ver_33 (1).csv


In [7]:
import pandas as pd
df = pd.read_csv('Book_ipl22_ver_33.csv')
df.head()

match_id           date                                         venue  \
0         1  March 26,2022                      Wankhede Stadium, Mumbai   
1         2  March 27,2022                     Brabourne Stadium, Mumbai   
2         3  March 27,2022            Dr DY Patil Sports Academy, Mumbai   
3         4  March 28,2022                      Wankhede Stadium, Mumbai   
4         5  March 29,2022  Maharashtra Cricket Association Stadium,Pune   

       team1      team2  stage toss_winner toss_decision  first_ings_score  \
0    Chennai    Kolkata  Group     Kolkata         Field               131   
1      Delhi     Mumbai  Group       Delhi         Field               177   
2   Banglore     Punjab  Group      Punjab         Field               205   
3    Gujarat    Lucknow  Group     Gujarat         Field               158   
4  Hyderabad  Rajasthan  Group   Hyderabad         Field               210   

   first_ings_wkts  second_ings_score  second_ings_wkts match_winner   won_by  \
0                5                133                 4      Kolkata  Wickets   
1                5                179                 6        Delhi  Wickets   
2                2                208                 5       Punjab  Wickets   
3                6                161                 5      Gujarat  Wickets   
4                6                149                 7    Rajasthan     Runs   

   margin player_of_the_match      top_scorer  highscore      best_bowling  \
0       6         Umesh Yadav        MS Dhoni         50      Dwayne Bravo   
1       4       Kuldeep Yadav    Ishan Kishan         81     Kuldeep Yadav   
2       5         Odean Smith  Faf du Plessis         88    Mohammed Siraj   
3       5      Mohammed Shami    Deepak Hooda         55    Mohammed Shami   
4      61        Sanju Samson   Aiden Markram         57  Yuzvendra Chahal   

  best_bowling_figure  
0               3--20  
1               3--18  
2               2--59  
3               3--25  
4               3--22

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pandas as pd

# One-hot encode categorical variables
df_encoded = pd.get_dummies(df, drop_first=True)

# Define the target column
y = df['match_winner']
X = df_encoded.drop(columns=[col for col in df_encoded.columns if col.startswith('match_winner_')])

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

# Evaluation
y_pred = model.predict(X_test_scaled)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("Classification Report:\n", classification_report(y_test, y_pred, zero_division=0))

Accuracy: 0.8
Confusion Matrix:
 [[1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]
Classification Report:
               precision    recall  f1-score   support

    Banglore       1.00      0.50      0.67         2
     Chennai       0.00      0.00      0.00         1
       Delhi       1.00      1.00      1.00         3
     Gujarat       1.00      1.00      1.00         4
     Kolkata       1.00      0.50      0.67         2
     Lucknow       0.50      1.00      0.67         1
      Mumbai       0.00      0.00      0.00         0
      Punjab       1.00      1.00      1.00         1
   Rajasthan       0.50      1.00      0.67         1

    accuracy                           0.80        15
   macro avg       0.67      0.67      0.63        15
weighted avg       0.87      0.80      0.80        15



In [11]:
y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("Classification Report:\n", classification_report(y_test, y_pred, zero_division=0))

Accuracy: 0.8
Confusion Matrix:
 [[1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]
Classification Report:
               precision    recall  f1-score   support

    Banglore       1.00      0.50      0.67         2
     Chennai       0.00      0.00      0.00         1
       Delhi       1.00      1.00      1.00         3
     Gujarat       1.00      1.00      1.00         4
     Kolkata       1.00      0.50      0.67         2
     Lucknow       0.50      1.00      0.67         1
      Mumbai       0.00      0.00      0.00         0
      Punjab       1.00      1.00      1.00         1
   Rajasthan       0.50      1.00      0.67         1

    accuracy                           0.80        15
   macro avg       0.67      0.67      0.63        15
weighted avg       0.87      0.80      0.80        15



In [12]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

# Initialize different models
decision_tree_model = DecisionTreeClassifier(random_state=42)
random_forest_model = RandomForestClassifier(random_state=42)
svm_model = SVC(random_state=42)
knn_model = KNeighborsClassifier()
nb_model = GaussianNB()

models = {
    "Logistic Regression": model,
    "Decision Tree": decision_tree_model,
    "Random Forest": random_forest_model,
    "SVM": svm_model,
    "K-Nearest Neighbors": knn_model,
    "Gaussian Naive Bayes": nb_model
}

# Train and evaluate each model
results = {}
for name, current_model in models.items():
    print(f"\n--- Evaluating {name} ---")


    if name == "Gaussian Naive Bayes":

        current_model.fit(X_train, y_train)
        y_pred_current = current_model.predict(X_test)
    else:
        current_model.fit(X_train_scaled, y_train)

        y_pred_current = current_model.predict(X_test_scaled)


    accuracy_current = accuracy_score(y_test, y_pred_current)
    confusion_matrix_current = confusion_matrix(y_test, y_pred_current)
    report_current = classification_report(y_test, y_pred_current, zero_division=0)

    print("Accuracy:", accuracy_current)
    print("Confusion Matrix:\n", confusion_matrix_current)
    print("Classification Report:\n", report_current)

    results[name] = {
        "Accuracy": accuracy_current,
        "Confusion Matrix": confusion_matrix_current,
        "Classification Report": report_current
    }

print("\n--- Performance Comparison ---")
for name, metrics in results.items():
    print(f"{name}: Accuracy = {metrics['Accuracy']:.4f}")


--- Evaluating Logistic Regression ---
Accuracy: 0.8
Confusion Matrix:
 [[1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]
Classification Report:
               precision    recall  f1-score   support

    Banglore       1.00      0.50      0.67         2
     Chennai       0.00      0.00      0.00         1
       Delhi       1.00      1.00      1.00         3
     Gujarat       1.00      1.00      1.00         4
     Kolkata       1.00      0.50      0.67         2
     Lucknow       0.50      1.00      0.67         1
      Mumbai       0.00      0.00      0.00         0
      Punjab       1.00      1.00      1.00         1
   Rajasthan       0.50      1.00      0.67         1

    accuracy                           0.80        15
   macro avg       0.67      0.67      0.63        15
weighted avg       0.87      0.80      0.80        15


--- Eva

In [14]:
team_wins = df['match_winner'].value_counts()

tournament_winner = team_wins.idxmax()
max_wins = team_wins.max()

print(f"\nPredicted Tournament Winner based on total match wins: {tournament_winner}")
print(f"Number of wins: {max_wins}")


Predicted Tournament Winner based on total match wins: Gujarat
Number of wins: 12
